---
title: "linear_models"
author: "Wenzhao Wu"
date: "11/22/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

model fitting

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

An good place to start is to consider price as an outcome that may depend on rating and borough. We fit that initial model in the following code.

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

```

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)

```

Tidying output

untidy fit results

```{r}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

tidy results

```{r}
fit %>% 
  broom::glance()
```

```{r}
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^borough", "Borough: ")) %>% 
  knitr::kable(digits = 3)
```

